export const FALLBACK_IMAGE_DATA_URL =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAIAAAACUFjqAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAnSURBVChTfccxDQAACAMw/MuYusngJT1I+nQm/Xh4eHh4eHh4+Ctd23KZ6cuSX/kAAAAASUVORK5CYII=";

export const ICON_SIZE = {
  l: 24,
  m: 18,
  s: 14,
};
